openapi: 3.0.3
info:
  title: OpenAPI schema for template rds-seeder
components:
  schemas:
    variables:
      required:
      - destination_address
      - source_address
      type: object
      properties:
        source_address:
          title: Source
          type: string
          description: Specify the seeding source address started with 'file://' or
            'http(s)://' schema.
          x-walrus-ui:
            group: Basic
        destination_address:
          title: Destination
          type: string
          description: Specify the seeding destiantion address.
          x-walrus-ui:
            group: Basic
        destination_conn_max:
          title: Destination Connection Maximum
          type: number
          description: Specify the connection maximum value of destination.
          default: 5
          x-walrus-ui:
            group: Advanced
        destination_batch_cap:
          title: Destination Batch Capacity
          type: number
          description: Specify the (insertion) batch capacity value of destination.
          default: 500
          x-walrus-ui:
            group: Advanced
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
          x-walrus-ui:
            group: Basic
            hidden: true
